from enum import StrEnum


class DocumentCategory(StrEnum):
    EXAM_QUESTIONS = "EXAM_QUESTIONS"
    ESSAY_QUESTIONS_AND_SELECTED_ANSWERS = "ESSAY_QUESTIONS_AND_SELECTED_ANSWERS"
    PERFORMANCE_TESTS_AND_SELECTED_ANSWERS = "PERFORMANCE_TESTS_AND_SELECTED_ANSWERS"
    FIRST_YEAR_LAW_STUDENT_EXAM = "FIRST_YEAR_LAW_STUDENT_EXAM"
    UNKNOWN = "UNKNOWN"


class SourceType(StrEnum):
    OFFICIAL_EXAM = "OFFICIAL_EXAM"
    OFFICIAL_SELECTED_ANSWERS = "OFFICIAL_SELECTED_ANSWERS"
    BAR_REVIEW_OUTLINE = "BAR_REVIEW_OUTLINE"
    USER_UPLOADED_OUTLINE = "USER_UPLOADED_OUTLINE"
    OTHER = "OTHER"


class IngestionStatus(StrEnum):
    DISCOVERED = "DISCOVERED"
    DOWNLOADED = "DOWNLOADED"
    EXTRACTED = "EXTRACTED"
    PARSED = "PARSED"
    FAILED = "FAILED"


class ReviewStatus(StrEnum):
    UNREVIEWED = "UNREVIEWED"
    AUTO_ACCEPTED = "AUTO_ACCEPTED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class LicenseStatus(StrEnum):
    UNKNOWN = "UNKNOWN"
    OFFICIAL_PUBLIC = "OFFICIAL_PUBLIC"
    PRIVATE_USE_ONLY = "PRIVATE_USE_ONLY"
    REDISTRIBUTABLE = "REDISTRIBUTABLE"


class RuleStatus(StrEnum):
    GENERAL = "GENERAL"
    TRADITIONAL = "TRADITIONAL"
    MAJORITY = "MAJORITY"
    MINORITY = "MINORITY"
    MODERN_TREND = "MODERN_TREND"
    UTC = "UTC"
    CALIFORNIA_SPECIFIC = "CALIFORNIA_SPECIFIC"
    EXCEPTION = "EXCEPTION"


class ComponentType(StrEnum):
    ELEMENT = "ELEMENT"
    EXCEPTION = "EXCEPTION"
    DEFINITION = "DEFINITION"
    EXAM_TIP = "EXAM_TIP"
    POLICY = "POLICY"
    EXAMPLE = "EXAMPLE"
    ALTERNATIVE_RULE = "ALTERNATIVE_RULE"
    MAJORITY_RULE = "MAJORITY_RULE"
    MINORITY_RULE = "MINORITY_RULE"
    TRADITIONAL_RULE = "TRADITIONAL_RULE"
    MODERN_RULE = "MODERN_RULE"
    REMEDY = "REMEDY"
    CONSEQUENCE = "CONSEQUENCE"

